#!/usr/bin/env bash
# Configures a new Ubuntu machine to install and configure Nginx

# Update package lists
apt-get update -y

# Install nginx
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

# Start nginx service (without using systemctl)
service nginx start
