#!/usr/bin/env bash
# Configures Nginx server with a 301 redirect for /redirect_me

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create a custom index.html
echo "Hello World!" > /var/www/html/index.html

# Add redirect rule to Nginx configuration
# The string to search for and the line to add after it
redirect_config="rewrite ^/redirect_me/?\$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Use sed to add the redirect after 'listen 80 default_server;'
sed -i "/listen 80 default_server;/a \\\t$redirect_config" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
