#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create a custom index.html
echo "Hello World!" > /var/www/html/index.html

# Create custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx with redirect for /redirect_me
redirect_config="rewrite ^/redirect_me/?\$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "/listen 80 default_server;/a \\\t$redirect_config" /etc/nginx/sites-available/default

# Configure custom 404 page
sed -i "/server_name _;/a \\\terror_page 404 /404.html;\\n\\tlocation = /404.html {\\n\\t\\tinternal;\\n\\t}" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
